
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MaulanaFH
 */
public class DataPeminjam extends javax.swing.JFrame {

    /**
     * Creates new form DataPeminjam
     */
    public DataPeminjam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbdata = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TFdenda = new javax.swing.JTextField();
        TFno = new javax.swing.JTextField();
        TFnama = new javax.swing.JTextField();
        TFjudul = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAalamat = new javax.swing.JTextArea();
        RDkembali = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField10 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        DCkembali = new com.toedter.calendar.JDateChooser();
        DCpinjam = new com.toedter.calendar.JDateChooser();
        RDbelum = new javax.swing.JRadioButton();
        CBbuku = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel3.setText("Login Admin Perpustakaan 'Meepawn'");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel4.setText("Login Admin Perpustakaan 'Meepawn'");

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel13.setText("Login Admin Perpustakaan 'Meepawn'");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Data Peminjam Buku Perpustakaan 'Meepawn'");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(140, 40, 460, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 0, 0);

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));
        jPanel6.setLayout(null);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);
        jButton1.setBounds(680, 20, 120, 30);

        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);
        jButton4.setBounds(30, 20, 140, 30);

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5);
        jButton5.setBounds(200, 20, 140, 30);

        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6);
        jButton6.setBounds(370, 20, 140, 30);

        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);
        jButton3.setBounds(530, 20, 120, 30);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 110, 810, 60);

        jPanel8.setBackground(new java.awt.Color(153, 153, 255));
        jPanel8.setLayout(null);

        tbdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Anggota", "Nama", "Alamat", "Jenis Buku", "Nama Buku", "Pinjam", "Kembali", "Denda", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbdata);
        if (tbdata.getColumnModel().getColumnCount() > 0) {
            tbdata.getColumnModel().getColumn(0).setResizable(false);
            tbdata.getColumnModel().getColumn(0).setHeaderValue("No Anggota");
            tbdata.getColumnModel().getColumn(1).setResizable(false);
            tbdata.getColumnModel().getColumn(1).setHeaderValue("Nama");
            tbdata.getColumnModel().getColumn(2).setResizable(false);
            tbdata.getColumnModel().getColumn(2).setHeaderValue("Alamat");
            tbdata.getColumnModel().getColumn(3).setResizable(false);
            tbdata.getColumnModel().getColumn(3).setHeaderValue("Jenis Buku");
            tbdata.getColumnModel().getColumn(4).setResizable(false);
            tbdata.getColumnModel().getColumn(4).setHeaderValue("Nama Buku");
            tbdata.getColumnModel().getColumn(5).setResizable(false);
            tbdata.getColumnModel().getColumn(5).setHeaderValue("Pinjam");
            tbdata.getColumnModel().getColumn(6).setResizable(false);
            tbdata.getColumnModel().getColumn(6).setHeaderValue("Kembali");
            tbdata.getColumnModel().getColumn(7).setResizable(false);
            tbdata.getColumnModel().getColumn(7).setHeaderValue("Denda");
            tbdata.getColumnModel().getColumn(8).setResizable(false);
            tbdata.getColumnModel().getColumn(8).setHeaderValue("Status");
        }

        jPanel8.add(jScrollPane3);
        jScrollPane3.setBounds(10, 20, 790, 590);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(jComboBox1);
        jComboBox1.setBounds(640, 130, 56, 20);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(0, 180, 810, 620);

        jPanel9.setBackground(new java.awt.Color(102, 102, 255));
        jPanel9.setLayout(null);
        getContentPane().add(jPanel9);
        jPanel9.setBounds(0, 790, 0, 60);

        jPanel10.setBackground(new java.awt.Color(102, 102, 255));
        jPanel10.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Status");
        jPanel10.add(jLabel1);
        jLabel1.setBounds(10, 580, 210, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No Anggota");
        jPanel10.add(jLabel2);
        jLabel2.setBounds(10, 50, 210, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama Anggota");
        jPanel10.add(jLabel6);
        jLabel6.setBounds(10, 110, 210, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Alamat Anggota");
        jPanel10.add(jLabel7);
        jLabel7.setBounds(10, 170, 210, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jenis Buku");
        jPanel10.add(jLabel8);
        jLabel8.setBounds(10, 280, 210, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Judul Buku");
        jPanel10.add(jLabel9);
        jLabel9.setBounds(10, 340, 210, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tanggal Pinjam");
        jPanel10.add(jLabel10);
        jLabel10.setBounds(10, 400, 210, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tanggal Kembali");
        jPanel10.add(jLabel11);
        jLabel11.setBounds(10, 460, 210, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Denda");
        jPanel10.add(jLabel12);
        jLabel12.setBounds(10, 520, 210, 20);
        jPanel10.add(TFdenda);
        TFdenda.setBounds(10, 540, 200, 30);
        jPanel10.add(TFno);
        TFno.setBounds(10, 70, 200, 30);
        jPanel10.add(TFnama);
        TFnama.setBounds(10, 130, 200, 30);
        jPanel10.add(TFjudul);
        TFjudul.setBounds(10, 360, 200, 30);

        TAalamat.setColumns(20);
        TAalamat.setRows(5);
        jScrollPane1.setViewportView(TAalamat);

        jPanel10.add(jScrollPane1);
        jScrollPane1.setBounds(10, 190, 200, 80);

        buttonGroup1.add(RDkembali);
        RDkembali.setText("Kembali");
        jPanel10.add(RDkembali);
        RDkembali.setBounds(20, 600, 110, 30);

        jPanel11.setBackground(new java.awt.Color(102, 102, 255));
        jPanel11.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Status");
        jPanel11.add(jLabel16);
        jLabel16.setBounds(10, 570, 210, 20);

        jLabel17.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Masukkan Data Peminjam");
        jPanel11.add(jLabel17);
        jLabel17.setBounds(10, 11, 210, 20);

        jLabel18.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("No Anggota");
        jPanel11.add(jLabel18);
        jLabel18.setBounds(10, 50, 210, 20);

        jLabel19.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Nama Anggota");
        jPanel11.add(jLabel19);
        jLabel19.setBounds(10, 110, 210, 20);

        jLabel20.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Alamat Anggota");
        jPanel11.add(jLabel20);
        jLabel20.setBounds(10, 170, 210, 20);

        jLabel21.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Jenis Buku");
        jPanel11.add(jLabel21);
        jLabel21.setBounds(10, 280, 210, 20);

        jLabel22.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Judul Buku");
        jPanel11.add(jLabel22);
        jLabel22.setBounds(10, 340, 210, 20);

        jLabel23.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Tanggal Pinjam");
        jPanel11.add(jLabel23);
        jLabel23.setBounds(10, 400, 210, 20);

        jLabel24.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Tanggal Kembali");
        jPanel11.add(jLabel24);
        jLabel24.setBounds(10, 460, 210, 20);

        jLabel25.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Denda");
        jPanel11.add(jLabel25);
        jLabel25.setBounds(10, 520, 210, 20);
        jPanel11.add(jTextField6);
        jTextField6.setBounds(10, 540, 200, 30);
        jPanel11.add(jTextField7);
        jTextField7.setBounds(10, 70, 200, 30);
        jPanel11.add(jTextField8);
        jTextField8.setBounds(10, 130, 200, 30);
        jPanel11.add(jTextField9);
        jTextField9.setBounds(10, 360, 200, 30);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel11.add(jScrollPane2);
        jScrollPane2.setBounds(10, 190, 200, 80);
        jPanel11.add(jTextField10);
        jTextField10.setBounds(10, 300, 200, 30);

        jRadioButton3.setText("Belum Kembali");
        jPanel11.add(jRadioButton3);
        jRadioButton3.setBounds(120, 590, 93, 23);

        jRadioButton4.setText("Kembali");
        jPanel11.add(jRadioButton4);
        jRadioButton4.setBounds(10, 590, 80, 23);

        jButton2.setText("Submit");
        jPanel11.add(jButton2);
        jButton2.setBounds(70, 630, 90, 30);

        jPanel10.add(jPanel11);
        jPanel11.setBounds(610, 110, 270, 670);

        jLabel26.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Masukkan Data Peminjam");
        jPanel10.add(jLabel26);
        jLabel26.setBounds(10, 11, 210, 20);
        jPanel10.add(DCkembali);
        DCkembali.setBounds(10, 480, 200, 30);
        jPanel10.add(DCpinjam);
        DCpinjam.setBounds(10, 420, 200, 30);

        buttonGroup1.add(RDbelum);
        RDbelum.setText("Belum Kembali");
        jPanel10.add(RDbelum);
        RDbelum.setBounds(140, 600, 120, 30);

        CBbuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<pilih salah satu>", "Novel", "Komik", "Majalah", "Buku Pelajaran", "Lain-Lain" }));
        CBbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBbukuActionPerformed(evt);
            }
        });
        jPanel10.add(CBbuku);
        CBbuku.setBounds(10, 300, 200, 30);

        getContentPane().add(jPanel10);
        jPanel10.setBounds(820, 110, 270, 690);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 880, 0);

        jLabel27.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Data Peminjam Buku Perpustakaan 'Meepawn'");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(390, 30, 510, 32);

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\if i ask.png")); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(-80, -90, 540, 350);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1090, 100);

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Copyright 2017 || Perpustakaan 'Meepawn'");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(420, 20, 330, 32);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 810, 1090, 70);
        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1090, 880);

        setSize(new java.awt.Dimension(1102, 922));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
TFnama.setText("");
TFno.setText("");
TAalamat.setText("");
CBbuku.setSelectedIndex(0);
TFjudul.setText("");
TFdenda.setText("");
buttonGroup1.clearSelection();
DCpinjam.setDate(null);
DCkembali.setDate(null);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    if ("".equals(TFno.getText()) || "".equals(TFnama.getText()) ||
            "".equals(TAalamat.getText()) ||"".equals(CBbuku.getSelectedIndex()) ||
            "".equals(TFjudul.getText()) || "".equals(DCpinjam.getDate()) ||
            "".equals(DCkembali.getDate()) || "".equals(TFdenda.getText())){
    JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
    }
    else {
    String kembali = "";
    if (RDkembali.isSelected()){
        kembali = "kembali";
    }else{
    kembali = "belum kembali";
    }
    String buku ="";
    if(CBbuku.getSelectedItem().equals("Majalah")){
    buku = "Majalah";
    }
    if(CBbuku.getSelectedItem().equals("Novel")){
    buku = "Novel";
    }
    if(CBbuku.getSelectedItem().equals("Komik")){
    buku = "Komik";
    }
    if(CBbuku.getSelectedItem().equals("Buku Pelajaran")){
    buku = "Buku Pelajaran";
    }
    if(CBbuku.getSelectedItem().equals("Lain-Lain")){
    buku = "Lain-Lain";
    }
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String tanggalpinjam = dateFormat.format(DCpinjam.getDate());
    String tanggalkembali = dateFormat.format(DCkembali.getDate());
    String SQL = "INSERT INTO tb_pinjam (no,Nama,Alamat,JenisBuku,JudulBuku,TglPinjam,TglKembali,Denda,Status)"
            + "VALUES('"+TFno.getText()+"','"+TFnama.getText()+"','"+TAalamat.getText()+"','"+buku
            +"','"+TFjudul.getText()+"','"+tanggalpinjam+"','"+tanggalkembali+"','"+TFdenda.getText()+"','"
            +kembali+"')";
    int status = 0;
        try {
            status = KoneksiDB.execute(SQL);
        } catch (SQLException ex) {
            Logger.getLogger(DataPeminjam.class.getName()).log(Level.SEVERE, null, ex);
        }
    if (status == 1){
    JOptionPane.showMessageDialog(this,"Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
        try {
            selectData();
        } catch (SQLException ex) {
            Logger.getLogger(DataPeminjam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }else {
        JOptionPane.showMessageDialog(this,"Data gagal ditambahkan","gagal",JOptionPane.WARNING_MESSAGE);
    
    }
    }
// TODO add your  "handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int baris = tbdata.getSelectedRow();
        if (baris != -1) {
        String No = tbdata.getValueAt(baris, 0).toString();
        String SQL = "DELETE FROM tb_pinjam WHERE no ='"+No+",";
        int status = 0;
            try {
                status = KoneksiDB.execute(SQL);
            } catch (SQLException ex) {
                Logger.getLogger(DataPeminjam.class.getName()).log(Level.SEVERE, null, ex);
            }
        if (status == 1){
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus","Sukses", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal", JOptionPane.WARNING_MESSAGE);
        }
        }
        else{
                 JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu","Error", JOptionPane.WARNING_MESSAGE);
                }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try {
            selectData();
        } catch (SQLException ex) {
            Logger.getLogger(DataPeminjam.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 MessageFormat header = new MessageFormat("Data transaksi peminjaman");
    MessageFormat footer = new MessageFormat("Page (0,number,integer)");
    try {
        tbdata.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
    }catch (java.awt.print.PrinterException e){
        System.err.format("Cannot print %s&n", e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CBbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBbukuActionPerformed
if(CBbuku.getSelectedItem().equals("Majalah")){
}        // TODO add your handling code here:
    }//GEN-LAST:event_CBbukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPeminjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBbuku;
    private com.toedter.calendar.JDateChooser DCkembali;
    private com.toedter.calendar.JDateChooser DCpinjam;
    private javax.swing.JRadioButton RDbelum;
    private javax.swing.JRadioButton RDkembali;
    private javax.swing.JTextArea TAalamat;
    private javax.swing.JTextField TFdenda;
    private javax.swing.JTextField TFjudul;
    private javax.swing.JTextField TFnama;
    private javax.swing.JTextField TFno;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable tbdata;
    // End of variables declaration//GEN-END:variables

    private void selectData() throws SQLException {
            String kolom[] = {"No","Nama","Alamat","JenisBuku","JudulBuku","TglPinjam","TglKembali","Denda","Status"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_pinjam";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while (rs.next()) {
                String no = rs.getString(1);
                String Nama = rs.getString(2);
                String Alamat = rs.getString(3);
                String JenisBuku = rs.getString(4);
                String JudulBuku = rs.getString(5);
                String TglPinjam = rs.getString(6);
                String TglKembali = rs.getString (7);
                String Denda = rs.getString (8);
                String Status = "";
                if ("Kembali".equals(rs.getString(9))) {
                    Status = "Kembali";
                } else {
                    Status = "Belum Kembali";
                }
                String data[] = {no,Nama,Alamat,JenisBuku,JudulBuku,TglPinjam,TglKembali,Denda,Status};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataPeminjam.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbdata.setModel(dtm);
    }
}
